obj-y  := \
  ipafsm90xx.o \
  timer.o \
  msm_init.o \
  lk_mmc_sdhci.o \
  lk_sdhci_msm.o \
  lk_sdhci.o \
  acpuclock.o \
  clock.o  clock_lib2.o  fsm9010-clock.o clock_pll.o lk_crc32.o \
  ike_api.o fastcall_tz.o

#partition_parser.o lk_mmc_wrapper.o

obj-$(CONFIG_CMD_KEY)   += key.o
obj-y += led.o secboot.o characterisation.o ipafsm90xx_fuse.o gpio.o

